---
#

#repository: docker.nexus.aetnadigital.com/simpleapp
#tag: 0.11.0

imagename: docker-publish.nexus.aetnadigital.net/simpleapp:0.14.3
  
replicas: 2

servicemonitor:
  enabled: true
  portname: actuator

ports:
# health check
  actuator:
    externalPort: 8081
    internalPort: 8081
  api:
    externalPort: 8082
    internalPort: 8082

specTemplateLabels:
  foo: bar

resources:
  requests:
    cpu: 300m
    memory: 1Gi
  limits:
    cpu: 300m
    memory: 1Gi

readinessProbe:
  httpGet:
    port: actuator
    path: /healthz
  initialDelaySeconds: 30
  periodSeconds: 30

livenessProbe:
  httpGet:
    port: actuator
    path: /healthz
  initialDelaySeconds: 30
  periodSeconds: 30

env:
  SIMPLEAPP_VAL: blue
  SPRING_APPLICATION_NAME: simpleapp-frontend
  SIMPLEAPP_CHECK_URL: http://simpleapp-frontend-backend.digital-cloud.svc:8080
  OPENTRACING_JAEGER_HTTP_SENDER_URL: http://simplest-collector.default.svc.cluster.local:14268/api/traces

secrets: {}

ingress:
  enabled: true
  class: nginx
  tls: false
