---
#

repository: docker.nexus.aetnadigital.com/simpleapp
tag: 0.9.0
  
replicas: 2

gateway:
  enabled: true
  hostPath: sample.192.168.146.166.xip.io
  hostOverride: sample2.192.168.146.166.xip.io
  tls:
    credentialName: foo-credential

servicemonitor:
  enabled: true
  portname: actuator

ports:
# health check
  actuator:
    externalPort: 8081
    internalPort: 8081

specTemplateLabels:
  foo: bar

resources:
  requests:
    cpu: 300m
    memory: 1Gi
  limits:
    cpu: 300m
    memory: 1Gi

readinessProbe:
  httpGet:
    port: actuator
    path: /healthz
  initialDelaySeconds: 30
  periodSeconds: 30

livenessProbe:
  httpGet:
    port: actuator
    path: /healthz
  initialDelaySeconds: 30
  periodSeconds: 30

env:
  SIMPLEAPP_VAL: blue
  SPRING_APPLICATION_NAME: simpleapp2
  SIMPLEAPP_CHECK_URL: 'http://ingester-svc.digital-cloud.svc:8080'

secrets: {}
