---
#

replicas: 2
rollout:
  enabled: true

servicemonitor:
  enabled: true
  portname: actuator

ports:
# health check
  actuator:
    externalPort: 8081
    internalPort: 8081

resources:
  requests:
    cpu: 300m
    memory: 2Gi
  limits:
    cpu: 300m
    memory: 2Gi

readinessProbe:
  httpGet:
    port: actuator
    path: /healthz
  initialDelaySeconds: 30
  periodSeconds: 30

livenessProbe:
  httpGet:
    port: actuator
    path: /healthz
  initialDelaySeconds: 30
  periodSeconds: 30

env:
  MY_VAR: sample

ingress:
  enabled: true
  tls: true