---
# look for simpleapp3 as override for second copy
repository: docker.nexus.aetnadigital.com/simpleapp
tag: 0.11.0

progressDeadlineSeconds: 120

service:
  selector:
    # override for second copy
    appSuffix: -primary # <<< call out primary

servicemonitor:
  enabled: true
  portname: actuator

ports:
  http:
    internalPort: 8080
    externalPort: 8080
  actuator:
    internalPort: 8081
    externalPort: 8081

resources:
  requests:
    cpu: 300m
    memory: 1Gi
  limits:
    cpu: 300m
    memory: 1Gi

readinessProbe:
  httpGet:
    port: actuator
    path: /healthz
  initialDelaySeconds: 30
  periodSeconds: 30

livenessProbe:
  httpGet:
    port: actuator
    path: /healthz
  initialDelaySeconds: 30
  periodSeconds: 30

env:
  SIMPLEAPP_VAL: blue
  SENTRY_ENVIRONMENT: dev
  # override for second copy
  SPRING_APPLICATION_NAME: simpleapp3
  SENTRY_TAGS: 'app:simpleapp,version:0.11.0'
  SIMPLEAPP_CHECK_URL: 'http://ingester-svc.digital-cloud.svc:8080'
  # simpleapp2
  #SENTRY_DSN: 'http://61f40485ea4a4542a93e154e14899dbb@sentry.sentry.svc:9000/5'
  # simpleapp
  #SENTRY_DSN: 'http://3dcb46e95cd3409ab670b7efd23a23c6@sentry.sentry.svc:9000/2'

secrets: {}

ingress:
  enabled: true
  class: nginx
  hostOverride: simpleapp3.192.168.1.29.xip.io
  tls: false

canary:
  enabled: true
  progressDeadlineSeconds: 900          # <==== 15 minutes

  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 4

  matches:
    # curl -H 'X-Canary: insider' http://simpleapp3.192.168.1.29.xip.io/
    - headers:
        x-canary:
          exact: "insider"
    # curl -b 'canary=always' http://simpleapp3.192.168.1.29.xip.io/
    - headers:
        cookie:
          exact: "canary"

  metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m

  webhooks:
    - name: load-test
      url: http://flagger-loadtester.test/
      timeout: 5s
      metadata:
        cmd: "hey -z 1m -q 10 -c 2 -H \"Cookie: canary=always\" http://simpleapp3.192.168.1.29.xip.io/"
