---
# Source: mycro-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: hyperion
  name: simpleapp-backend
  labels:
    app: simpleapp-backend
    app.kubernetes.io/part-of: simpleapp-backend
  annotations:
    prometheus.io/probe: "true"
spec:
  type: ClusterIP
  ports:
    - name: actuator
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: api
      port: 8082
      protocol: TCP
      targetPort: 8082
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080 
  selector:
    app: simpleapp-backend
---
# Source: mycro-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hyperion
  name: simpleapp-backend
  annotations:
    author: "health-cloud"
    app.kubernetes.io/instance: simpleapp-backend
    app.kubernetes.io/part-of: simpleapp-backend
    app.kubernetes.io/name: simpleapp-backend
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: simpleapp-backend
  template:
    metadata:
      labels:
        app: simpleapp-backend
        app.kubernetes.io/part-of: simpleapp-backend
        version: v1
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/scape: "true"
        prometheus.io/port: "8080"
    spec:
      imagePullSecrets:
        - name: registry
      containers:
        - name: simpleapp-backend
          image: "docker.nexus.aetnadigital.net/simpleapp:0.12.9"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 1Gi
          ports:
            - name: actuator
              containerPort: 8081
            - name: api
              containerPort: 8082
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: actuator
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: actuator
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: OPENTRACING_JAEGER_HTTP_SENDER_URL
              value: "http://simplest-collector.hyperion.svc.cluster.local:14268/api/traces"
            - name: SIMPLEAPP_VAL
              value: "simpleapp-backend"
            - name: SPRING_APPLICATION_NAME
              value: "simpleapp-backend"
---
# Source: mycro-service/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: servicemonitor
metadata:
  name: simpleapp-backend
  namespace: hyperion
  labels:
    app: simpleapp-backend
    app.kubernetes.io/part-of: simpleapp-backend
    release: prometheus-operator-chart
spec:
  selector:
    matchLabels:
      app: simpleapp-backend
  namespaceSelector:
    matchNames:
      - hyperion
  endpoints:
  - port: actuator
    scheme: http
    path: /metrics
    interval: 15s
    honorLabels: true
