{{- if .Values.ingress.enabled -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ include "ns" . }}
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: {{.Values.ingress.class | default "nginx" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    prometheus.io/probe: "true"
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- if .Values.ingress.hostOverride }}
  - host: {{ .Values.ingress.hostOverride }}
  {{- else }} 
  - host: {{ include "hostname" . }}
  {{- end }}
    http:
      paths:
        - path: {{ .Values.ingress.path | default "/" }}
          backend:
            serviceName: {{ .Release.Name }}
            servicePort: {{ .Values.ports.http.externalPort }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    {{- if .Values.ingress.hostOverride }}
      - {{ .Values.ingress.hostOverride }}
    {{- else }} 
      - {{ include "hostname" . }}
    {{- end }}  
    {{- if .Values.ingress.tlsSecret }}
    secretName: {{ .Values.ingress.tlsSecret }}
    {{- end -}}
  {{- end }}
{{- end }}